# Generated by Django 3.2.4 on 2021-06-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('title', models.CharField(default='Untitled', max_length=127, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('language', models.CharField(max_length=7, verbose_name='language')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
        ),
    ]
