# Generated by Django 3.2.4 on 2021-06-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_q', '0015_auto_20210612_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127, verbose_name='title')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('credentials', models.JSONField(verbose_name='credentials')),
                ('settings', models.JSONField(verbose_name='settings')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='docker_host.host', verbose_name='host')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_jobs', to='django_q.task', verbose_name='task')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', models.IntegerField(default=0, verbose_name='permissions')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='docker_host.host', verbose_name='host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.UniqueConstraint(fields=('host', 'user'), name='unique_permissions_for_user'),
        ),
    ]
