# Generated by Django 3.2.4 on 2021-06-12 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docker_host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=127, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='docker_host.host', verbose_name='host')),
            ],
        ),
    ]
