# Generated by Django 3.2.4 on 2021-06-16 07:05

from django.db import migrations, models
import monitoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='last_launch',
            field=models.DateTimeField(default=monitoring.models.default_last_launch, verbose_name='last_launch'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='next_launch',
            field=models.DateTimeField(auto_now_add=True, verbose_name='next_launch'),
        ),
    ]
