# Generated by Django 3.2.4 on 2021-06-19 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0003_auto_20210617_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlnotification',
            name='users',
        ),
        migrations.AddField(
            model_name='htmlnotification',
            name='users',
            field=models.ManyToManyField(related_name='html_notifications', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
