# Generated by Django 3.2.4 on 2021-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_htmlnotification_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlnotification',
            name='subject',
            field=models.CharField(default='Dodja', max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='htmlnotification',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
